packages:
  - "www"
  - "owner"
  - "tenantv3"
  - "watermark"
  - "df-shared-next"
  - "e2e-tests"
  - "storybook"

catalog:
  # dependencies
  axios: 1.9.0
  "@gouvfr/dsfr": 1.11.2
  "@sentry/vue": 9.20.0
  "@sentry/vite-plugin": 3.4.0
  pinia: 3.0.2
  vee-validate: 4.15.0
  vue: 3.5.14
  vue-i18n: 11.1.3
  vue-router: 4.5.1
  # devDependencies
  "@intlify/unplugin-vue-i18n": 6.0.8
  vite: 6.3.5
  vitest: 3.1.4
  vue-tsc: 2.2.10
  typescript: 5.8.3
  prettier: 3.5.3
  eslint: 8.57.1
  eslint-plugin-vue: 9.32.0
  "@vue/tsconfig": 0.7.0
  "@tsconfig/node18": 18.2.4
  "@vitejs/plugin-vue": 5.2.4
  "@types/node": 22.15.19
