packages:
  - "www"
  - "owner"
  - "tenantv3"
  - "watermark"
  - "df-shared-next"
  - "e2e-tests"
  - "storybook"

catalog:
  # dependencies
  axios: 1.9.0
  "@gouvfr/dsfr": 1.13.2
  "@sentry/vue": 9.22.0
  "@sentry/vite-plugin": 3.5.0
  pinia: 3.0.2
  vee-validate: 4.15.0
  vue: 3.5.18
  vue-i18n: 11.1.11
  vue-router: 4.5.1
  # devDependencies
  "@intlify/unplugin-vue-i18n": 6.0.8
  vite: 7.0.6
  vitest: 3.2.4
  vue-tsc: 3.0.4
  typescript: 5.9.2
  prettier: 3.5.3
  eslint: 9.32.0
  eslint-plugin-vue: 10.4.0
  jiti: 2.4.2
  "@vue/tsconfig": 0.7.0
  "@tsconfig/node18": 18.2.4
  "@vitejs/plugin-vue": 6.0.1
  "@types/node": 24.1.0
  "@vitest/eslint-plugin": 1.3.4
  "@vue/eslint-config-prettier": 10.2.0
  "@vue/eslint-config-typescript": 14.6.0
  "@gouvminint/vue-dsfr": 8.4.0
