<template>
  <BackLinkRow :label="t('france-identite')" :to="parent" category="france-identité" />
  <i18n-t :keypath="'add-doc-' + textKey" tag="p">
    <template #proof
      ><strong>{{ t('proof') }}</strong></template
    >
    <template #valid
      ><strong>{{ t('valid') }}</strong></template
    >
    <template #france-identite
      ><a
        href="https://france-identite.gouv.fr/"
        :title="`France Identité - ${t('new-window')}`"
        target="_blank"
        >France Identité</a
      ></template
    >
  </i18n-t>
  <div class="display--flex blue-text fr-mb-2w">
    <button type="button" class="fr-btn fr-btn--secondary" @click="showFIModal = true">
      {{ t('see-example') }} <RiEyeLine class="fr-ml-1v" />
    </button>
  </div>
  <UploadFilesIdentity category="FRANCE_IDENTITE" />
  <ModalComponent v-if="showFIModal" @close="showFIModal = false">
    <template #header>
      <!-- TODO change to a h1 when migrating modals -->
      <h2 class="fr-h3">{{ t('france-id-example-title') }}</h2>
    </template>
    <template #body>
      <p>{{ t('france-id-example-text') }}</p>
      <img :src="franceIdentiteImage" alt="" />
    </template>
    <template #footer>
      <DfButton type="button" primary @click="showFIModal = false">{{ t('modal.close') }}</DfButton>
    </template>
  </ModalComponent>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { useParentRoute } from '@/components/common/lib/useParentRoute'
import BackLinkRow from './lib/IdentityBackRow.vue'
import UploadFilesIdentity from './lib/UploadFilesIdentity.vue'
import { RiEyeLine } from '@remixicon/vue'
import ModalComponent from 'df-shared-next/src/components/ModalComponent.vue'
import franceIdentiteImage from '@/assets/ex_justi_france_identite.png'
import DfButton from 'df-shared-next/src/Button/DfButton.vue'
import { ref } from 'vue'
import { useIdentificationState } from './lib/identityDocumentState'

const parent = useParentRoute()
const { t } = useI18n()
const { textKey } = useIdentificationState()

const showFIModal = ref(false)
</script>

<i18n>
{
  "en": {
    "add-doc-tenant": "Add a single-use {valid} {proof} generated by {france-identite}",
    "add-doc-guarantor": "Add a single-use {valid} {proof} for your guarantor generated by {france-identite}",
    "add-doc-couple": "Add a single-use {valid} {proof} for your spouse generated by {france-identite}",
    "add-doc-couple-guarantor": "Add a single-use {valid} {proof} for their guarantor generated by {france-identite}",
    "proof": "proof of identity",
    "valid": "valid",
    "see-example": "See an example of a France Identité document",
    "france-id-example-title": "Example of France Identité document",
    "france-id-example-text": "The document is entitled « Justificatif d’identité à usage unique ». It contains the following information: surname, first names, gender, nationality, date and place of birth. A QR code allows its authenticity to be verified."
  },
  "fr": {
    "add-doc-tenant": "Ajoutez un {proof} {valid} à usage unique généré par {france-identite}.",
    "add-doc-guarantor": "Ajoutez un {proof} de votre garant {valid} à usage unique généré par {france-identite}.",
    "add-doc-couple": "Ajoutez un {proof} de votre conjoint {valid} à usage unique généré par {france-identite}.",
    "add-doc-couple-guarantor": "Ajoutez un {proof} de son garant {valid} à usage unique généré par {france-identite}.",
    "proof": "justificatif d’identité",
    "valid": "en cours de validité",
    "see-example": "Voir un exemple de justificatif France Identité",
    "france-id-example-title": "Exemple de justificatif France identité",
    "france-id-example-text": "Le document est intitulé « Justificatif d’identité à usage unique ». Il comporte les informations suivantes: nom, prénoms, sexe, nationalité date et lieu de naissance. Un QR code permet de vérifier son authenticité."
  }
}
</i18n>
