<template>
  <BackLinkRow :label="t('france-identite')" :to="parent" category="france-identité" />
  <i18n-t :keypath="'add-doc-' + textKey" tag="p">
    <template #proof
      ><strong>{{ t('proof') }}</strong></template
    >
    <template #valid
      ><strong>{{ t('valid') }}</strong></template
    >
    <template #france-identite
      ><a href="https://france-identite.gouv.fr/" target="_blank">France Identité</a></template
    >
  </i18n-t>
  <div class="display--flex blue-text fr-mb-2w">
    <RiInformationLine />
    <button type="button" class="fi-btn" @click="showFIModal = true">
      {{ t('see-example') }}
    </button>
  </div>
  <UploadFilesIdentity category="FRANCE_IDENTITE" />
  <ModalComponent v-if="showFIModal" @close="showFIModal = false">
    <template #header>
      <h2 class="fr-h3">{{ t('france-id-example') }}</h2>
    </template>
    <template #body>
      <img :src="franceIdentiteImage" :alt="t('unique-id-doc')" />
    </template>
    <template #footer>
      <DfButton type="button" primary @click="showFIModal = false">{{ t('modal.close') }}</DfButton>
    </template>
  </ModalComponent>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { useParentRoute } from '@/components/common/lib/useParentRoute'
import BackLinkRow from './lib/IdentityBackRow.vue'
import UploadFilesIdentity from './lib/UploadFilesIdentity.vue'
import { RiInformationLine } from '@remixicon/vue'
import ModalComponent from 'df-shared-next/src/components/ModalComponent.vue'
import franceIdentiteImage from '@/assets/ex_justi_france_identite.png'
import DfButton from 'df-shared-next/src/Button/DfButton.vue'
import { ref } from 'vue'
import { useIdentificationState } from './lib/identityDocumentState'

const parent = useParentRoute()
const { t } = useI18n()
const { textKey } = useIdentificationState()

const showFIModal = ref(false)
</script>

<style scoped>
.fi-btn {
  text-align: left;
}
</style>

<i18n>
{
  "en": {
    "add-doc-tenant": "Add a single-use {valid} {proof} generated by {france-identite}",
    "add-doc-guarantor": "Add a single-use {valid} {proof} for your guarantor generated by {france-identite}",
    "add-doc-couple": "Add a single-use {valid} {proof} for your spouse generated by {france-identite}",
    "proof": "proof of identity",
    "valid": "valid",
    "see-example": "See an example of a France Identité document",
    "france-id-example": "Example of France Identité document",
    "unique-id-doc": "Single-use identity document"
  },
  "fr": {
    "add-doc-tenant": "Ajoutez un {proof} {valid} à usage unique généré par {france-identite}.",
    "add-doc-guarantor": "Ajoutez un {proof} de votre garant {valid} à usage unique généré par {france-identite}.",
    "add-doc-couple": "Ajoutez un {proof} de votre conjoint {valid} à usage unique généré par {france-identite}.",
    "proof": "justificatif d’identité",
    "valid": "en cours de validité",
    "see-example": "Voir un exemple de justificatif France Identité",
    "france-id-example": "Exemple de justificatif France identité",
    "unique-id-doc": "Justificatif d’identité à usage unique"
  }
}
</i18n>
